name: Run Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DEPLOY_HOST1: api
  DEPLOY_HOST2: web
  DEPLOY_HOST3: execution

jobs:
  deploy:
  timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node_version: 18
  deploy-api:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy API Server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST1 }}
      run: |
        cd apps/api
        npm install --legacy-peer-deps
        yarn dev
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy WEB Server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST2 }}
      run: |
        cd apps/web
        npm install --legacy-peer-deps
        yarn dev
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Npm Install and Execution Tests
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST3 }}
      run: | 
        npm install
        npx playwright install --with-deps
        npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30