name: Run Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  Deploy-API-Server:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node_version: 18
    - name: Deploy API Server
      run: |
        cd apps/api
        npm install --legacy-peer-deps
        yarn dev
  Deploy-WEB-Server:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node_version: 18
    - name: Deploy WEB Server
      run: |
        cd apps/web
        npm install --legacy-peer-deps
        yarn dev
  Execution-Tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: ${{ always() }}
      needs: [ Deploy-API-Server,Deploy-WEB-Server ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node_version: 18
    - name: Npm Install and Execution Tests
      run: | 
        npm install
        npx playwright install --with-deps
        npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30