name: Run Playwright tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ${{ ubuntu-latest }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
